name: Call a reusable workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'releases/**'
    tags:
      - 'v*'
env:
  MDTDB_VER: 18.4

jobs:
  call-workflow-16:
    uses: ./.github/workflows/docker-build.yml
    with:
      BASE_IMAGE: docker.idatatlas.com/postgres:16.2
      MDTDB_VERSION: 18.4
      PG_HINT_PLAN_VERSION: REL16_1_6_0
      PGAUDIT_VERSION: 16.0
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      NEXUS: ${{ secrets.NEXUS }}

  call-workflow-15:
    uses: ./.github/workflows/docker-build.yml
    with:
      BASE_IMAGE: docker.idatatlas.com/postgres:15.6
      MDTDB_VERSION: 18.4
      PG_HINT_PLAN_VERSION: REL15_1_5_1
      PGAUDIT_VERSION: 1.7.0
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      NEXUS: ${{ secrets.NEXUS }}