name: Call a reusable workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'releases/**'
    tags:
      - 'v*'

jobs:
  call-workflow:
    uses: ./.github/workflows/docker-build.yml
    with:
      BASE_IMAGE: docker.idatatlas.com/postgres:16.2
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}